services:
  calebmateo-filesync:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    labels:
      project: "kazoku"
      service: "calebmateo-filesync"
      environment: "production"
      version: "2.0.0"
